import type {
  ClientOnboardingRequest,
  ClientOnboardingResponse,
} from '@conomyhq/core';
import type { Transport } from '../transport';

/**
 * Clients resource. Today the only operation modeled is the onboarding
 * bootstrap — `POST /clients/{clientId}/onboarding` — which materializes
 * a brand-new CLIENT identity tree (CLIENT + ESCROW accounts + ORG +
 * STAFF + accounts + rules) in one call.
 *
 * Auth: the path runs under users-composite's InternalSession middleware
 * (X-Internal-Api-Key + conomyhq-client-id header). The api-client
 * transport sends the operator's Bearer token; the gateway swaps it for
 * the internal headers before forwarding to users-composite. Callers
 * don't need to think about either header.
 *
 * `clientId` is generated by the caller (typically operations' approve
 * saga via `primitive.NewObjectID().Hex()`) and lands BOTH in the URL
 * path and inside the request body when the consumer wants to be
 * explicit. Mismatch = 400 from users-composite.
 */
export class ClientsModule {
  constructor(private readonly transport: Transport) {}

  /**
   * Bootstrap a brand-new CLIENT identity tree.
   *
   *   await api.clients.onboarding(clientId, { client, currencies, … });
   */
  onboarding(
    clientId: string,
    body: ClientOnboardingRequest,
  ): Promise<ClientOnboardingResponse> {
    return this.transport.request<ClientOnboardingResponse>(
      `/clients/${encodeURIComponent(clientId)}/onboarding`,
      { method: 'POST', body: { ...body, clientId: body.clientId ?? clientId } },
    );
  }
}
